### ISSUE TITLE
Issue with Optimizely Jquery Polyfill

### ISSUE THREAD

**Issue by tomhanlon** [clearhead/clearhead#16]
Hey @casecode,

Can we discuss tomorrow? Getting [this error](https://i.clrhd.me/th/2015-08-31_16-55-21.png) on [this page](https://www.plaingreenloans.com/) after building [this src folder](https://github.com/clearhead/clearhead-experiments/tree/master/think-finance/exp-1.0-home-sweet-home). 

Thanks

**Comment by casecode** [comment]
@tomhanlon - No issue with polyfill. Your usage is incorrect. You need to pass your instance of jQuery is the first (and only) parameter. See test for example: https://github.com/clearhead/clearhead/blob/master/test/optimizely-jquery-polyfill.js.

I will add more docs to clarify as well.
