### ISSUE TITLE
goal.js adds a trailing dash to goal names

### ISSUE THREAD

**Issue by beaulm** [clearhead/clearhead#20]
For example:

`goal('exp-x-test');` tracks `exp-x-test-`

**Comment by tomhanlon** [comment]
Hey Beau,

I think this is happening because you need to be passing two arguments: exp-x as the first string and the goal string as the second. 

TH

**Comment by beaulm** [comment]
I thought by binding it to a property I could just pass in the goal string, which in this case is 'exp-x-test'.

```javascript
const goal = require('clearhead/goal').bind(null, 'prop13');
goal('exp-1-initiative-click-mlp-logo-click');
```

**Comment by tomfuertes** [comment]
Maybe

const goal = require('clearhead/goal').bind(null, 'prop13', 'exp-1');

goal('initiative-click-mlp-logo-click');


On Fri, Sep 18, 2015 at 10:32 AM, beaulm <notifications@github.com> wrote:

> I thought by binding it to a property I could just pass in the goal
> string, which in this case is 'exp-x-test'.
>
> const goal = require('clearhead/goal').bind(null, 'prop13');
> goal('exp-1-initiative-click-mlp-logo-click');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clearhead/clearhead/issues/20#issuecomment-141483856>.
>



-- 
Tom Fuertes | (512) 913-1086
http://www.linkedin.com/in/tomfuertes

**Comment by tomfuertes** [comment]
Maybe

```
const goal = require('clearhead/goal').bind(null, 'prop13', 'exp-1');
goal('initiative-click-mlp-logo-click');
```

**Comment by tomfuertes** [comment]
As a temporary work around us that. I'll patch shortly b/c label is supposed to be optional but not working that way

**Comment by beaulm** [comment]
And that'll work ok with Omniture/SiteCatalyst?

**Comment by tomfuertes** [comment]
Should right?

https://github.com/clearhead/clearhead/blob/master/src/goal.js#L48

**Comment by tomfuertes** [comment]
Fixed in https://github.com/clearhead/clearhead/commit/aef6c590a76b997f9f5cfc024af5c7b855a5cb34

**Comment by tomfuertes** [comment]
Bumped 0.0.34 in clearhead-experiments - can you re npm install and confirm it's working as expected?

**Comment by beaulm** [comment]
Yup, looks better!
